run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - unused
    - gosimple
    - typecheck

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

