agent:
  name: "test-agent-from-config"
  system_prompt: "You are a helpful assistant configured via YAML."
  model: "openai::gpt-4o"
  working_dir: "/home/verte/Desktop/sandbox"
  persistence: "json"
  tools:
    - "fs"
    - "git"
  subagents:
    reasoning: "deepseek::deepseek-reasoner"
  plugins:
    - "logger"
vector-storage:
  vector_db: "sqlite"
  embedding_model: "openai::text-embedding-3-small"
  sqlite:
    db_path: "/home/verte/Desktop/sandbox/vector_db/chroma.db"
