agent:
  name: "test-agent-from-config"
  system_prompt: "You are a helpful assistant configured via YAML."
  model: "deepseek::deepseek-chat"
  working_dir: "/home/verte/Desktop/sandbox"
  persistence: "json"
  tools:
    - "fs"
    - "git"
  subagents:
    reasoning: "deepseek::deepseek-chat"
    vector: "deepseek::deepseek-chat"
  plugins:
    - "logger"
    - "todo"

vector-storage:
  vector_db: "sqlite"
  embedding_model: "openai::text-embedding-3-small"
  sqlite:
    db_path: "./vector.db"
  # milvus:
  #   endpoint: "localhost:19530"
